# Jeevs Edition — Batch 02b: Anemia I · Impaired Production — UWorld depth gaps
# Source: UWorld articles "Anemia: Iron deficiency anemia", "Anemia: Approach to anemia",
# "Anemia: Anemia of chronic disease/Anemia of inflammation", "Pernicious anemia",
# plus Gastroenterology "Vitamin deficiencies and toxicities".
# Written to close depth gaps the course review file (§4-§6) does not cover.
Q = []

def q(stem, choices, correct, explanation, wrong, eli5, image=None, imcap=None, exim=None, excap=None):
    d = {"stem": stem, "choices": choices, "correct": correct, "explanation": explanation,
         "wrongExplanations": wrong, "eli5": eli5}
    if image: d["image"] = image; d["imageCaption"] = imcap
    if exim: d["explanationImage"] = exim; d["explanationImageCaption"] = excap
    Q.append(d)

# ════════ PART 3 — Q31–Q35: UWorld-sourced gaps ════════
# Source: UWorld articles "Anemia: Iron deficiency anemia", "Anemia: Approach to anemia",
# "Anemia: Anemia of chronic disease/Anemia of inflammation", "Pernicious anemia".

# ── 1. Iron-containing enzymes, not just hemoglobin (§4) ─────────────────
q("A 38-year-old woman comes to the office because of a 6-month history of fatigue and an uncomfortable urge to move her legs that begins each evening when she lies down and is relieved by walking. Her menstrual periods last 7 days with passage of clots. Examination shows pallor, a smooth tongue, fissuring at both corners of the mouth, and concave, spoon-shaped fingernails.\n\nLaboratory studies show:\nHemoglobin 9.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 28% (N=36%–46%)\nMean corpuscular volume 70 µm3 (N=80–100 µm3)\nSerum ferritin 4 ng/mL (N=10–120 ng/mL)\nTransferrin saturation 6% (N=20%–50%)\nSerum vitamin B12 480 pg/mL (N=200–900 pg/mL)\n\nWhich of the following best explains this patient's leg symptoms?",
  ["A. Deficient dopamine synthesis from impaired tyrosine hydroxylase activity", "B. Demyelination of the dorsal columns from methylmalonic acid accumulation", "C. Peripheral axonal degeneration from thiamine deficiency", "D. Reduced oxygen delivery causing anaerobic muscle metabolism", "E. Small-fiber neuropathy from chronic hyperglycemia"],
  0,
  "Iron does more than build hemoglobin. About 80% of body iron sits in hemoglobin and, to a lesser degree, myoglobin — but iron is also a cofactor for a family of IRON-CONTAINING ENZYMES, and losing those produces the non-anemic features of iron deficiency.\n\nThis patient has a textbook cluster of them:\n• RESTLESS LEGS SYNDROME — iron is the cofactor for TYROSINE HYDROXYLASE, the rate-limiting enzyme of dopamine synthesis → dopaminergic dysfunction in the substantia nigra and spinal motor pathways → the urge to move, worse at rest and relieved by movement.\n• GLOSSITIS (smooth tongue) and ANGULAR CHEILITIS — epithelium has rapid turnover and fails first when iron-dependent enzymes of DNA synthesis and repair are lost.\n• KOILONYCHIA (spoon nails) and alopecia, by the same mechanism.\n• PICA is the other classic, though its mechanism is unclear.\n\nThe point worth carrying: iron deficiency can cause symptoms through enzyme failure even before, or out of proportion to, the anemia. Iron repletion improves restless legs in deficient patients.",
  {"1": "Methylmalonic acid accumulation and dorsal column demyelination is the mechanism of subacute combined degeneration in vitamin B12 deficiency. Her B12 is normal at 480 pg/mL, and her anemia is microcytic rather than macrocytic.",
   "2": "Thiamine deficiency causes dry beriberi — a symmetric sensorimotor peripheral neuropathy — typically with chronic alcohol use or malnutrition. It does not produce an urge to move relieved by walking, and it does not cause microcytosis.",
   "3": "Reduced oxygen delivery explains her fatigue, weakness and exertional dyspnea, and it is the surface-read answer because it is the obvious consequence of anemia. It does not produce a circadian, rest-triggered urge to move that resolves with movement, and it would not explain the nail and tongue findings.",
   "4": "Small-fiber neuropathy from hyperglycemia causes burning, stocking-distribution pain in long-standing diabetes. Nothing here suggests diabetes, and the symptom pattern described is characteristic of restless legs rather than a painful neuropathy."},
  "Iron is not only for carrying oxygen — some enzymes need it too, including the one that helps make dopamine. Running low on iron upsets that, which is what makes her legs restless at night.")

# ── 2. Ferritin versus hemosiderin (§4) ──────────────────────────────────
q("An investigator is studying how the body stores iron. Iron is isolated from macrophages of the spleen, liver, and bone marrow in two forms. The first is a hollow, spherical protein shell that can hold several thousand iron atoms in a soluble mineral core, and from which iron can be released quickly when demand rises. The second is an insoluble, amorphous aggregate of iron mixed with partially degraded protein, from which iron cannot be rapidly retrieved.\n\nThe first form described is which of the following?",
  ["A. Ferritin", "B. Hemosiderin", "C. Hepcidin", "D. Myoglobin", "E. Transferrin"],
  0,
  "Because free iron is toxic, the roughly 20% of body iron that is not in hemoglobin, myoglobin or enzymes is held in one of two storage forms, and they differ in how fast the iron can be recovered:\n\n• FERRITIN — a hollow, spherical protein that stores several thousand iron atoms as a soluble mineral core. Iron in ferritin can be RAPIDLY MOBILIZED to meet demand. It is found mainly in hepatocytes, and also in macrophages of marrow, liver and spleen. A small amount leaks into serum in proportion to total stores, which is why SERUM FERRITIN is the best marker of iron stores — and why it rises as an acute phase reactant regardless of stores.\n• HEMOSIDERIN — an insoluble, amorphous aggregate of iron with partially degraded ferritin, found mainly in mononuclear phagocytes that cull old red cells. Because it is insoluble it CANNOT be rapidly mobilized. It is what the Prussian blue stain demonstrates in marrow macrophages.\n\nSo ferritin is the accessible reserve; hemosiderin is the locked-away remainder.",
  {"1": "Hemosiderin is the second form described — insoluble, amorphous, and not rapidly mobilizable. It is the form whose absence on a marrow Prussian blue stain establishes depleted stores.",
   "2": "Hepcidin is not a storage molecule at all; it is the liver-derived regulatory peptide that degrades ferroportin and thereby blocks iron export from enterocytes and macrophages.",
   "3": "Myoglobin is a functional iron protein that holds oxygen in muscle. It belongs to the 80% functional compartment, not the storage compartment.",
   "4": "Transferrin is the plasma TRANSPORT protein that carries iron between compartments. It holds only about 3 mg of iron at any moment and is measured indirectly as the total iron-binding capacity."},
  "The body keeps spare iron in two ways: one is like a jar you can open quickly, the other is like iron set in concrete. Ferritin is the jar.")

# ── 3. Heme versus non-heme iron (§4) ────────────────────────────────────
q("A 29-year-old woman comes to the office because of a 5-month history of fatigue. She has followed a strict vegan diet for 3 years and deliberately eats iron-rich foods including spinach, lentils, and fortified cereal every day. Her menstrual periods are regular and light. She has no gastrointestinal symptoms and has had no surgery.\n\nLaboratory studies show:\nHemoglobin 10.1 g/dL (N=12.0–16.0 g/dL)\nHematocrit 30% (N=36%–46%)\nMean corpuscular volume 75 µm3 (N=80–100 µm3)\nSerum ferritin 7 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 441 µg/dL (N=250–400 µg/dL)\nSerum vitamin B12 320 pg/mL (N=200–900 pg/mL)\n\nWhich of the following best explains her iron deficiency despite adequate dietary iron intake?",
  ["A. Heme iron requires intrinsic factor for absorption", "B. Inorganic iron must be reduced to the ferrous state and is absorbed far less efficiently", "C. Non-heme iron is absorbed only in the terminal ileum", "D. Phytates in plant foods chelate heme iron specifically", "E. Vegetables contain negligible quantities of iron"],
  1,
  "Dietary iron comes in two chemically different forms, and they are absorbed with very different efficiency:\n\n• HEME IRON, from animal meat, is transported directly into the intestinal epithelial cell as an intact heme molecule. Absorption is relatively efficient — roughly 20% of what is consumed.\n• INORGANIC (NON-HEME) IRON, from plants, exists mostly in the FERRIC (Fe³⁺) state. It must first be REDUCED to the FERROUS (Fe²⁺) state by duodenal ferrireductase, aided by gastric acid, before the divalent metal transporter can carry it in. Absorption is much less efficient — estimated at under 5% of what is consumed.\n\nSo a vegan diet can contain plenty of iron on paper while delivering very little into the body. UWorld lists individuals on vegetarian or vegan diets — particularly women of childbearing age, who also have menstrual losses — among the groups at risk of dietary iron deficiency. Her ferritin of 7 ng/mL with a raised binding capacity confirms true depletion.\n\nPractical consequences: take non-heme iron with vitamin C (which reduces Fe³⁺ to Fe²⁺), and avoid taking it with tea, calcium or antacids.",
  {"0": "Intrinsic factor is required for VITAMIN B12 absorption, not iron. Her B12 is normal, and heme iron enters the enterocyte directly without any carrier protein from the stomach.",
   "2": "Iron of both kinds is absorbed proximally, in the DUODENUM. The terminal ileum is where the B12–intrinsic factor complex is absorbed, and confusing the two sites is the error this option is built on.",
   "3": "Phytates, tannins and calcium do impair iron absorption, so this is the tempting near-miss. They chelate NON-HEME iron; heme iron is comparatively protected from them, which is the opposite of what the option states.",
   "4": "Plant foods such as lentils, spinach and fortified cereal genuinely contain substantial iron — the problem is bioavailability, not quantity. If her intake were truly negligible the counselling would be different."},
  "Iron from meat is absorbed easily, but iron from plants is in a form the gut first has to convert, and most of it never gets in. So her diet looks iron-rich on paper but delivers very little.")

# ── 4. Pernicious anemia also causes iron deficiency (§5) ────────────────
q("A 61-year-old woman with pernicious anemia has received intramuscular cyanocobalamin every month for 8 months. Before treatment her hemoglobin concentration was 8.6 g/dL with a mean corpuscular volume of 118 µm3. She reports improved energy but remains fatigued on exertion. A test of the stool for occult blood is negative on three samples, and upper endoscopy 2 months ago showed atrophic mucosa in the gastric body and fundus with no mass or ulcer.\n\nLaboratory studies show:\nHemoglobin 10.2 g/dL (N=12.0–16.0 g/dL)\nHematocrit 31% (N=36%–46%)\nMean corpuscular volume 74 µm3 (N=80–100 µm3)\nSerum vitamin B12 620 pg/mL (N=200–900 pg/mL)\nMethylmalonic acid 0.18 µmol/L (N=0.08–0.40 µmol/L)\nSerum ferritin 6 ng/mL (N=10–120 ng/mL)\nTotal iron-binding capacity 455 µg/dL (N=250–400 µg/dL)\nSerum gastrin 680 pg/mL (N=<100 pg/mL)\n\nWhich of the following best explains this patient's persistent anemia?",
  ["A. Coexisting iron deficiency from achlorhydria", "B. Development of gastric adenocarcinoma with occult blood loss", "C. Inadequate dosing of parenteral vitamin B12", "D. Myelodysplastic syndrome", "E. Persistent folate deficiency"],
  0,
  "Her B12 problem is fixed — the B12 is 620 pg/mL and the methylmalonic acid has normalized — yet she is still anemic, and her MCV has swung from 118 µm3 all the way down to 74 µm3. Something microcytic was hiding underneath the macrocytosis, and the iron studies name it: ferritin 6 ng/mL with a raised binding capacity.\n\nThe mechanism is the same autoimmune lesion. Pernicious anemia destroys PARIETAL CELLS, and parietal cells make BOTH intrinsic factor AND gastric acid. Losing acid causes ACHLORHYDRIA → dietary ferric (Fe³⁺) iron is not reduced to the absorbable ferrous (Fe²⁺) form → IRON DEFICIENCY develops alongside the B12 deficiency.\n\nThe raised gastrin is the corroborating clue: the antrum is SPARED in autoimmune gastritis, so its G cells survive, and loss of acid removes the negative feedback on them → hypergastrinemia.\n\nWhile both deficiencies coexist, the opposing effects on cell size can cancel out and the MCV can read normal — a dimorphic picture. Treating the B12 alone unmasked the iron deficiency. She needs iron replacement as well.",
  {"1": "Pernicious anemia does raise the long-term risk of gastric adenocarcinoma and carcinoid, so this must be considered — it is the reason these patients need surveillance. Three negative stool occult blood tests and a recent endoscopy showing no mass make occult tumor bleeding unlikely here.",
   "2": "Inadequate B12 dosing would leave the B12 low and the methylmalonic acid high, and the cells would stay macrocytic. Both values are now normal and the MCV has fallen below the reference range.",
   "3": "Myelodysplastic syndrome is a consideration for a persistent unexplained anemia in an older adult, but it typically gives a NORMAL or HIGH MCV with dysplastic changes and often other cytopenias — not microcytosis with an empty ferritin.",
   "4": "Folate deficiency produces a MACROcytic anemia, which is the opposite of her current picture, and it would not lower the ferritin."},
  "The same immune attack that stopped her stomach making the B12 helper protein also stopped it making acid — and acid is needed to absorb iron. Fixing the B12 revealed the iron problem that was hidden underneath.")

# ── 5. Functional iron deficiency on an ESA (§6) ─────────────────────────
q("A 64-year-old man with end-stage kidney disease has received hemodialysis three times weekly for 3 years. He has been treated with epoetin alfa for 18 months, and his dose was increased 6 weeks ago without improvement in his hemoglobin concentration. He has no bleeding, and a test of the stool for occult blood is negative.\n\nLaboratory studies show:\nHemoglobin 9.2 g/dL (N=13.5–17.5 g/dL)\nHematocrit 28% (N=41%–53%)\nMean corpuscular volume 88 µm3 (N=80–100 µm3)\nReticulocyte count 0.8% (N=0.5%–1.5%)\nSerum ferritin 180 ng/mL (N=20–250 ng/mL)\nTransferrin saturation 14% (N=20%–50%)\nC-reactive protein 0.6 mg/dL (N=<1.0 mg/dL)\n\nWhich of the following is the most appropriate next step in management?",
  ["A. Increase the erythropoiesis-stimulating agent dose further", "B. Intravenous iron sucrose", "C. Oral ferrous sulfate", "D. Transfusion of packed red blood cells", "E. Vitamin B12 injection"],
  1,
  "This is FUNCTIONAL IRON DEFICIENCY: the ferritin says the stores are adequate (180 ng/mL) but the TRANSFERRIN SATURATION of 14% says almost no iron is reaching the marrow. An erythropoiesis-stimulating agent has ordered the marrow to build red cells at a rate its iron supply cannot sustain, so the reticulocyte count stays flat however much drug is given.\n\nTwo things block the supply in dialysis patients: chronically raised HEPCIDIN, which degrades ferroportin and traps iron in macrophages and enterocytes, and ongoing dialysis-circuit blood losses.\n\nThe route matters. UWorld's rule for anemia of inflammation is that iron is generally ineffective in isolated disease, but IS useful in mixed iron deficiency or in FUNCTIONAL IRON DEFICIENCY in chronic kidney disease patients on an erythropoiesis-stimulating agent — and INTRAVENOUS iron is preferred, because oral absorption is unreliable when hepcidin is high. Giving intravenous iron restores the substrate and lets the agent work at a lower dose.",
  {"0": "Escalating the agent without correcting the iron supply is the error the vignette describes — the dose was already raised 6 weeks ago with no response. Higher doses raise the risk of hypertension, stroke and thrombosis without producing red cells the marrow lacks the iron to build.",
   "2": "Oral iron is poorly absorbed in dialysis patients because hepcidin degrades the ferroportin the enterocyte needs to export iron. It is a reasonable trial in mild cases but is not the preferred route here.",
   "3": "Transfusion is reserved for severe or symptomatic anemia and hemodynamic compromise. It also risks iron overload and alloimmunization, which matters for a patient who may need a kidney transplant.",
   "4": "Vitamin B12 deficiency would give a macrocytic anemia with a raised methylmalonic acid. His MCV is 88 µm3 and there is nothing to suggest a B12 problem."},
  "His kidney medicine is telling the marrow to build red cells, but the marrow has no iron delivered to build them with. Iron given into the vein bypasses the blocked gut and supplies it.")
