# Vascular Disease (Ciraulo) — Image Quiz V2, 18 items, every stem has an image; topics and angles differ from V1
Q = [
dict(img='Vbluetoe', cap='Photograph of the right foot',
stem="A 74-year-old man with a known 4.8-cm abdominal aortic aneurysm has sudden painful discoloration of several toes (shown). The foot is warm, and dorsalis pedis and posterior tibial pulses are easily palpable.{FIG}Which of the following is the most appropriate next step to find the cause?",
choices=["Aortoiliac CT angiogram","Plain x-ray of the foot","Venous duplex of the leg","Nerve conduction studies","Toe amputation"], key=0,
exp="This is <b>blue toe syndrome</b>: <b>small cholesterol emboli</b> from upstream plaque or an aneurysm (more common with aneurysmal disease), with <b>palpable pedal pulses</b> because the big arteries are open. Dr. Ciraulo: \"It's not a blue toe because there's a problem with the knee, it's a blue toe because there's probably a problem upstream.\" Image the source: <b>CTA of the aorta and iliac arteries</b> (his aneurysm is the leading suspect). Blue toe can be the presenting sign of aortoiliac disease, and an aneurysm that embolizes is an indication to repair.<br><br><b>Educational objective:</b> Blue toes with normal pulses mean microemboli from a proximal source. Image the aorta and iliacs.",
wrong={1:"A foot x-ray shows bone, not the embolic source.",
2:"Venous duplex looks for DVT, which doesn't cause blue toes with livedo-like patches.",
3:"This is ischemia, not neuropathy.",
4:"The tissue may recover, and amputation doesn't address the source."},
eli5="Tiny bits of cholesterol are breaking off something upstream (probably his aneurysm) and plugging the toe arteries. You find and fix the source."),

dict(img='Vrubor', cap='Photograph of the legs with the feet hanging down',
stem="A 77-year-old woman with diabetes who smokes wakes most nights with burning pain in her forefoot that eases when she hangs her foot over the side of the bed. Her feet are shown in a dependent position; pedal pulses are absent, and the ankle-brachial index is 0.32.{FIG}Which of the following is the most appropriate management?",
choices=["Urgent revascularization referral","Supervised walking program alone","Cilostazol and follow-up in 6 months","Compression stockings","Reassurance; this is neuropathic pain"], key=0,
exp="Pain at <b>rest</b>, at <b>night</b>, relieved by <b>dangling the leg</b> (gravity helps perfusion), dependent rubor, absent pulses and an ABI around 0.3 mean <b>critical limb ischemia</b>. That's limb-threatening: 30% progress to major amputation within a year and 25% die within a year. Dr. Ciraulo: crossing the line from claudication to rest pain is \"an indication to get someone to a vascular surgeon.\" Indications for intervention: lifestyle-limiting claudication, <b>ischemic rest pain</b>, tissue loss.<br><br><b>Educational objective:</b> Ischemic rest pain (relieved by dependency, with a very low ABI) is critical limb ischemia and needs urgent revascularization.",
wrong={1:"Exercise therapy is for claudication, not rest pain.",
2:"Cilostazol treats claudication. Waiting 6 months risks limb loss.",
3:"Compression reduces arterial inflow and is harmful in severe arterial disease.",
4:"Relief with dependency and a very low ABI point to ischemia, not neuropathy."},
eli5="Her foot is so starved of blood that it hurts even lying in bed, and hanging it down lets gravity push a bit more blood in. She needs a surgeon to restore the blood flow."),

dict(img='Vlathromb', cap='Axial contrast CT of the chest (arrow)',
stem="An 80-year-old woman with atrial fibrillation who stopped her anticoagulant 3 weeks ago has a sudden painful, pale, cold right leg with absent popliteal and pedal pulses. Sensation is reduced but she can move her toes. A chest CT obtained for another reason is shown.{FIG}Which of the following is the first treatment?",
choices=["Intravenous unfractionated heparin","Oral aspirin","Cilostazol","Immediate below-knee amputation","Compression stockings"], key=0,
exp="The CT shows a filling defect in the <b>left atrium</b>: the commonest source of arterial emboli (mural thrombus in <b>atrial fibrillation</b>). Acute limb ischemia (the P's) from an embolus. Slide 31: <b>anticoagulation is always the first step</b>, and <b>IV heparin is the drug of choice</b>, to stop propagation. Then, with motor and sensory function still intact, percutaneous thrombectomy or catheter-directed thrombolysis is preferred, or open <b>Fogarty embolectomy</b>. Then long-term anticoagulation for the source.<br><br><b>Educational objective:</b> Acute embolic limb ischemia is treated first with IV heparin, then clot removal, then prevention of recurrence (anticoagulation for AF).",
wrong={1:"Aspirin doesn't stop clot propagation in acute arterial occlusion.",
2:"Cilostazol is for chronic claudication.",
3:"The limb is viable (motor function intact), so salvage comes first.",
4:"Compression is for venous disease and would worsen arterial ischemia."},
eli5="A clot from her heart (off her blood thinner) shot down into her leg. First give heparin so the clot stops growing, then go get it out."),

dict(img='Vfasc', cap='Intraoperative photograph of the lower leg',
stem="A 66-year-old man had a femoral embolectomy for a 7-hour-old occlusion. Four hours later his calf is tense and exquisitely painful on passive toe dorsiflexion, and the first web space is numb. He undergoes the procedure shown.{FIG}Which of the following best explains the complication that required this procedure?",
choices=["Reperfusion edema inside the fascia","Recurrent embolus to the popliteal artery","Deep venous thrombosis of the calf","Peroneal nerve compression from positioning","Infection of the arteriotomy site"], key=0,
exp="The photo shows a <b>fasciotomy</b> with muscle bulging through the released fascia. After revascularization, <b>reperfusion injury</b> (\"like putting peroxide right into the bloodstream\") generates oxygen free radicals that damage capillary membranes. Muscle swells inside its fascia until tissue pressure exceeds perfusion, causing <b>compartment syndrome</b> and ischemia again. Signs: pain on passive stretch, calf tenderness, numbness of the first web space (deep peroneal nerve). Treatment: <b>fasciotomy</b>, decided on clinical findings. Re-examine every couple of hours after revascularization.<br><br><b>Educational objective:</b> Compartment syndrome after revascularization comes from reperfusion injury and is treated with fasciotomy.",
wrong={1:"A new embolus gives a pulseless limb, not a tense, swollen compartment.",
2:"DVT causes swelling but not first web-space numbness with pain on passive stretch.",
3:"Positioning palsy doesn't cause a tense, painful compartment.",
4:"Infection takes days and doesn't present this way."},
eli5="When blood rushed back into the starved muscle, it swelled up inside its tight sleeve until it choked itself. Cutting the sleeve open gives the muscle room."),

dict(img='Vctadis', cap='Sagittal CT angiogram of the chest',
stem="A 61-year-old man with poorly controlled hypertension has tearing pain between his shoulder blades. Blood pressure is 182/104 mm Hg in both arms, pulses are intact, and urine output and lactate are normal. CT angiography (shown) demonstrates a dissection flap that begins just distal to the left subclavian artery; the ascending aorta is normal.{FIG}Which of the following is the most appropriate initial management?",
choices=["IV β-blocker, then a vasodilator if needed","Emergent open ascending aortic replacement","IV nitroprusside alone as the first drug","Thrombolysis to clear the false lumen","Immediate pericardiocentesis"], key=0,
exp="A dissection starting distal to the left subclavian with a normal ascending aorta is <b>DeBakey III / Stanford B</b>. Uncomplicated (no rupture, malperfusion or end-organ failure) → <b>medical BP control</b>. \"If you control the hypertension, sometimes these dissections will heal.\" Failure or complications → <b>TEVAR</b>. Board add-on: start an <b>IV β-blocker</b> (esmolol, labetalol) to a heart rate ≤ 60 and systolic BP 100–120, then add a vasodilator. A vasodilator alone causes reflex tachycardia and more shear stress on the aorta.<br><br><b>Educational objective:</b> Uncomplicated Stanford B dissection is treated with BP and heart-rate control (β-blocker first). TEVAR is for complications.",
wrong={1:"Open repair is for type A (ascending) dissections.",
2:"Nitroprusside first causes reflex tachycardia and more aortic shear stress.",
3:"Thrombolysis in a dissection is contraindicated.",
4:"Tamponade is a type A complication, and his pulses and pressure are fine."},
eli5="The tear is in the part of the aorta past the heart's branches. Lowering his pulse and blood pressure takes the strain off and lets it settle."),

dict(img='Vaaact', cap='Axial contrast CT of the abdomen',
stem="A 79-year-old man has vague back discomfort; his blood pressure is 148/88 mm Hg and he is hemodynamically stable. CT of the abdomen is shown.{FIG}Which of the following is the most appropriate management?",
choices=["Open or endovascular repair","Ultrasound surveillance every 6 months","Ultrasound surveillance every 3 months","Repeat CT in 1 year","No action unless it ruptures"], key=0,
exp="The CT shows an <b>infrarenal abdominal aortic aneurysm about 9 cm</b> across, measured on the outer wall (thrombus lines the lumen). Indications for repair: <b>> 5.5 cm</b>, <b>symptomatic</b> (his back discomfort counts), growth > 5 mm in 6 months, saccular shape. Rupture risk rises steeply with size (slide: > 5.5 cm → 3–15%), and rupture presents with severe back pain and shock. <b>EVAR</b> needs a neck > 15 mm, angle < 60°, adequate access arteries and < 50% calcification; otherwise open repair.<br><br><b>Educational objective:</b> An AAA > 5.5 cm or one causing symptoms should be repaired.",
wrong={1:"Six-monthly ultrasound is for aneurysms < 4.5 cm.",
2:"Three-monthly ultrasound is for 4.5–5.0 cm.",
3:"Waiting a year with a 9 cm aneurysm risks rupture.",
4:"Rupture carries very high mortality. Repair beforehand."},
eli5="His aorta has ballooned to about three times normal. At that size it can burst, so it needs fixing."),

dict(img='Vischcol', cap='Endoscopic view of the sigmoid colon',
stem="On the first night after open repair of an infrarenal aortic aneurysm, a 72-year-old man on norepinephrine passes several maroon, bloody stools. Flexible sigmoidoscopy is shown.{FIG}Which intraoperative decision would most likely have prevented this complication?",
choices=["Re-implanting an IMA with weak back-bleeding","Ligating an IMA with pulsatile back-bleeding","Using an aortobifemoral rather than a tube graft","Clamping the aorta above the renal arteries","Giving more intravenous fluid before the clamp"], key=0,
exp="Bloody stool after aortic surgery is <b>ischemic colitis</b> (the sigmoid), typically in the first 12–24 h. \"The surgeon didn't operate on his GI tract, why is he pooping blood?\" The IMA decision: when the IMA is cut during aortic replacement, <b>pulsatile back-bleeding</b> means good collateral flow from the SMA, so it can be tied off. <b>A weak trickle of back-bleeding</b> means the colon depends on the IMA, so <b>re-implant it</b>. A thrombosed IMA was never contributing. Vasopressors and blood loss add to the low flow.<br><br><b>Educational objective:</b> Ischemic colitis after aortic repair comes from loss of IMA flow. Re-implant the IMA when its back-bleeding is weak.",
wrong={1:"Pulsatile back-bleeding means good collaterals, so ligation is appropriate.",
2:"Graft configuration doesn't decide colonic perfusion. The IMA does.",
3:"A suprarenal clamp adds renal ischemia without protecting the colon.",
4:"Volume helps perfusion but isn't the key decision the question is about."},
eli5="The artery feeding the lower colon was tied off, and this patient's colon had no backup supply. If the cut artery barely bleeds back, the colon depends on it, so it should be sewn back on."),

dict(img='Vsplenic', cap='Axial contrast CT of the upper abdomen (measurement shown)',
stem="A 31-year-old woman who is planning a pregnancy has an incidental finding on CT done for kidney stones (shown): a calcified, 2.6-cm aneurysm arising from the splenic artery. She is asymptomatic.{FIG}Which of the following is the most appropriate management?",
choices=["Repair now (endovascular or open)","Observe; repair only if symptoms appear","Repeat CT after the pregnancy","Start a β-blocker and observe","Splenectomy only if it ruptures"], key=0,
exp="<b>Splenic artery aneurysms</b>: risk factors <b>female sex, multiple pregnancies, HTN</b>. Usually asymptomatic, but they <b>rupture in pregnancy</b> (\"mom has a baby… next thing you know, mom's coding\"), often as a \"double rupture\" (into the lesser sac, then free into the abdomen). <b>Repair if > 2 cm, symptomatic, or in a woman of child-bearing age</b>, and treat <b>before</b> pregnancy: endovascular stent graft or embolization, or open ligation.<br><br><b>Educational objective:</b> Splenic artery aneurysms in women of child-bearing age (or > 2 cm or symptomatic) should be repaired, ideally before pregnancy.",
wrong={1:"Waiting for symptoms risks rupture, especially in pregnancy.",
2:"Pregnancy is when rupture risk is highest. Treat before.",
3:"A β-blocker doesn't prevent rupture of a visceral aneurysm.",
4:"Rupture in pregnancy has high maternal and fetal mortality."},
eli5="This kind of aneurysm is known to burst during pregnancy, so it's fixed before she gets pregnant."),

dict(img='Vpopl', cap='Angiogram of the distal thigh and knee',
stem="A 70-year-old man has a pulsatile mass behind his right knee. Angiography is shown; the aneurysm measures 3 cm.{FIG}Which complication is this lesion most likely to cause if left untreated?",
choices=["Distal embolization or thrombosis","Free rupture into the popliteal fossa","High-output heart failure","Compression of the femoral nerve","Infective endocarditis"], key=0,
exp="<b>Popliteal aneurysms</b>: <b>primarily men</b>, often a <b>palpable pulsatile mass behind the knee</b>. Unlike aortic aneurysms, they rarely rupture. Symptoms come from <b>embolization to the feet or thrombosis</b> (acute limb ischemia). Repair if <b>> 2 cm or symptomatic</b>: ligation with bypass or interposition graft, endovascular repair, or thrombolysis followed by repair. Board add-on: often bilateral and associated with an AAA, so image the other knee and the aorta.<br><br><b>Educational objective:</b> Popliteal aneurysms threaten the limb through embolization and thrombosis, not rupture. Repair if > 2 cm or symptomatic.",
wrong={1:"Popliteal aneurysms rarely rupture.",
2:"High-output failure comes from AV fistulas, not aneurysms.",
3:"The femoral nerve isn't in the popliteal fossa (the tibial and peroneal nerves are).",
4:"Endocarditis is unrelated."},
eli5="Clot builds up inside the bulge behind the knee. Either it blocks the artery or bits break off and plug the foot arteries."),

dict(img='Vsma', cap='Coronal CT angiogram of the abdomen (arrows)',
stem="An 83-year-old woman with atrial fibrillation who is not anticoagulated has 6 hours of severe periumbilical pain; she is writhing, but her abdomen is soft and only mildly tender. Lactate is 4.1 mmol/L. CT angiography is shown.{FIG}Which of the following is the most appropriate management?",
choices=["Embolectomy and lifelong anticoagulation","Bowel rest and IV antibiotics only","Aortomesenteric bypass for chronic stenosis","Upper endoscopy","Repeat CT in 24 hours"], key=0,
exp="Elderly + <b>atrial fibrillation</b> + abdominal pain = \"a 911 event.\" The CTA shows an occlusion in the <b>SMA</b> (arrows): an <b>embolus</b>, which lodges past the first jejunal branches. Board add-on: pain out of proportion to the exam is the classic clue. Treatment by cause: <b>embolus → embolectomy + anticoagulation</b> (lifelong: \"if you have a thrombus once, your heart's gonna have thrombus again\") · thrombosis → aortomesenteric bypass · non-occlusive (vasospasm) → bowel rest, antibiotics, fluids · venous → anticoagulation · dead bowel → resection. \"When in doubt, operate.\"<br><br><b>Educational objective:</b> SMA embolus from AF is treated with urgent embolectomy, assessment and resection of dead bowel, and lifelong anticoagulation.",
wrong={1:"Bowel rest and antibiotics are for non-occlusive mesenteric ischemia.",
2:"Bypass is for acute thrombosis on a chronic stenosis, not an embolus.",
3:"Endoscopy doesn't treat or diagnose mesenteric arterial occlusion.",
4:"Waiting lets the bowel die."},
eli5="A clot from her heart blocked the main artery to her intestines. The surgeon has to pull it out fast, check for dead bowel, and keep her on blood thinners for life."),

dict(img='Vrasmra', cap='MR angiogram of the abdominal aorta and kidneys (arrow)',
stem="A 67-year-old man who smokes has hypertension that remains uncontrolled on four drugs, and he has had two episodes of sudden pulmonary edema with a normal ejection fraction. MR angiography is shown.{FIG}Which mechanism best explains his hypertension?",
choices=["Renin–angiotensin activation from low renal flow","Primary overproduction of aldosterone by an adrenal adenoma","Catecholamine excess from a pheochromocytoma","Excess cortisol from a pituitary adenoma","Increased sympathetic tone from obstructive sleep apnea"], key=0,
exp="The MRA shows <b>renal artery stenosis</b> (arrow). <b>Goldblatt hypertension</b> (\"if you do nothing else for kidneys, learn that word\"): the kidney senses low flow → <b>↑ renin → angiotensin II</b> (vasoconstriction) and <b>aldosterone</b> (Na⁺ and water reabsorption) → hypertension. Suspect it with HTN <b>refractory to medication</b>, <b>pulmonary edema out of proportion</b> to left-heart failure, or HTN in children and young adults. In an older smoker the cause is usually atherosclerosis; in a young woman, fibromuscular dysplasia. Tests: captopril scintigraphy, renal vein renin, duplex, CTA/MRA. Treatment: angioplasty/stent, bypass, endarterectomy or nephrectomy.<br><br><b>Educational objective:</b> Renal artery stenosis causes renovascular (Goldblatt) hypertension through renin–angiotensin–aldosterone activation.",
wrong={1:"An adrenal adenoma causes primary hyperaldosteronism with <b>low</b> renin. Here renin is driving it.",
2:"Pheochromocytoma gives episodic headaches, sweating and palpitations.",
3:"Cushing disease gives central obesity, striae and hyperglycemia.",
4:"Sleep apnea contributes to resistant HTN but wouldn't explain the imaging or flash pulmonary edema."},
eli5="A narrowed kidney artery fools the kidney into thinking blood pressure is too low, so it pumps out hormones that raise the pressure everywhere else."),

dict(img='Vraynaud', cap='Photograph of the hand after cold exposure',
stem="A 24-year-old woman has episodes in which her fingers turn sharply white when she holds a cold drink (shown), then blue, then red and throbbing as they rewarm. She has no rash, joint pain, skin thickening or ulcers, and antinuclear antibodies are negative. Avoiding cold has not been enough.{FIG}Which of the following is the most appropriate drug?",
choices=["Nifedipine","Propranolol","Sumatriptan","Prednisone","Warfarin"], key=0,
exp="<b>Raynaud phenomenon</b>: episodic, exaggerated <b>vasospasm</b> in response to <b>cold or emotion</b>, with <b>pallor → cyanosis → rubor</b>. With no systemic disease this is <b>primary</b> Raynaud (secondary is linked to autoimmune disease). Management: avoid cold (heated gloves), then <b>calcium channel blockers</b> (board add-on: nifedipine). Surgical <b>sympathectomy</b> is rare. Board add-on: avoid vasoconstrictors such as β-blockers and triptans.<br><br><b>Educational objective:</b> Raynaud phenomenon (white → blue → red) is treated with cold avoidance and a calcium channel blocker such as nifedipine.",
wrong={1:"β-blockers can worsen vasospasm (unopposed α).",
2:"Triptans are vasoconstrictors and worsen Raynaud.",
3:"Steroids are for vasculitis (GCA, Takayasu), not primary vasospasm.",
4:"This is vasospasm, not thrombosis."},
eli5="Her finger arteries clamp down too hard in the cold. Nifedipine relaxes artery muscle so they don't clamp shut."),

dict(img='Vgca', cap='Photograph of the side of the head (arrow)',
stem="A 76-year-old woman has 3 weeks of new temporal headaches, fatigue, low-grade fever, and pain in her jaw when chewing. This morning she noticed brief blurring in her right eye. The finding at the arrow is tender. ESR is 92 mm/h.{FIG}Which of the following is the most appropriate next step?",
choices=["Start high-dose corticosteroids now","Wait for temporal artery biopsy before treatment","Prescribe ibuprofen and follow up in 2 weeks","Order carotid duplex and start aspirin","Begin a triptan for migraine"], key=0,
exp="A thickened, tender superficial temporal artery with new headache, <b>jaw claudication</b>, fever, fatigue and a very high ESR in an older patient means <b>giant cell (temporal) arteritis</b>, a large-vessel vasculitis. Lecture: <b>temporal artery biopsy</b> confirms it and <b>corticosteroids</b> treat it. Board add-on: with visual symptoms, <b>start steroids immediately</b>, without waiting for the biopsy (still valid for 1–2 weeks on steroids), to prevent irreversible blindness from ophthalmic artery ischemia.<br><br><b>Educational objective:</b> Suspected giant cell arteritis, especially with visual symptoms, is treated with immediate high-dose corticosteroids, then confirmed by temporal artery biopsy.",
wrong={1:"Delaying steroids risks permanent vision loss.",
2:"NSAIDs don't control the vasculitis.",
3:"Carotid disease doesn't explain jaw claudication, fever and the ESR.",
4:"Triptans are vasoconstrictors and wrong for vasculitis."},
eli5="Her temple artery is inflamed and the same inflammation can block the artery to her eye. Steroids calm it down fast, so you start them before the biopsy result."),

dict(img='Vtaka', cap='3D CT angiogram of the aortic arch and branches',
stem="A 25-year-old woman has 4 months of fever, myalgia and weight loss, and now her left arm aches when she blow-dries her hair. The left radial pulse is weak, and blood pressure is 30 mm Hg lower in the left arm. CT angiography is shown.{FIG}Which of the following is the most likely diagnosis?",
choices=["Takayasu arteritis","Giant cell arteritis","Fibromuscular dysplasia","Thromboangiitis obliterans","Atherosclerotic subclavian stenosis"], key=0,
exp="<b>Takayasu disease</b>: a <b>large-vessel vasculitis of the aorta and its branches</b> (and the pulmonary vessels) in <b>young females</b>. Constitutional symptoms (fever, myalgia, weight loss), pain, and stenoses or aneurysms; the aorta looks lumpy and irregular on imaging. Board add-on: \"pulseless disease,\" with arm claudication, weak pulses and a BP difference between arms. Diagnosis: <b>digital subtraction angiography</b> (CTA/MRA). Treatment: <b>steroids</b>, and consider revascularization.<br><br><b>Educational objective:</b> A young woman with constitutional symptoms, arm claudication and unequal arm pulses has Takayasu arteritis, treated with steroids.",
wrong={1:"GCA affects people over 50 (jaw claudication, temporal headache).",
2:"FMD affects renal and carotid arteries in young women without systemic inflammation.",
3:"Buerger disease affects small distal vessels in male smokers.",
4:"Atherosclerosis is unlikely at 25, and it doesn't cause fever and weight loss."},
eli5="Her immune system is inflaming the big arteries coming off her heart, which narrows the one to her left arm. That's why the pulse is weak and the arm aches with use."),

dict(img='Vbuerger', cap='Photograph of the hand and a hand angiogram',
stem="A 35-year-old man who smokes two packs a day has painful dusky fingers and a fingertip ulcer (shown, left). He also had tender red cords on his forearm last year. Radial and ulnar pulses are palpable. His hand angiogram is shown on the right.{FIG}Which intervention is most likely to prevent amputation?",
choices=["Complete smoking cessation","Lifelong warfarin","High-dose corticosteroids","Surgical bypass to the digital arteries","Nifedipine"], key=0,
exp="<b>Thromboangiitis obliterans (Buerger disease)</b>: inflammatory occlusion of <b>small and medium arteries and veins</b> in <b>male smokers</b>. Proximal pulses are preserved and distal ones lost; claudication and paresthesia; board add-on: migratory superficial thrombophlebitis. The angiogram shows distal occlusions with <b>corkscrew collaterals</b>. The <b>only effective treatment is smoking cessation</b>. Dr. Ciraulo: \"You don't stop smoking, your hand's coming off, pick one.\"<br><br><b>Educational objective:</b> Buerger disease (young male smoker, distal ischemia, corkscrew collaterals) is treated by complete smoking cessation.",
wrong={1:"Anticoagulation doesn't stop the disease while he smokes.",
2:"It isn't a steroid-responsive vasculitis like GCA or Takayasu.",
3:"The digital vessels are too small and diffusely diseased to bypass.",
4:"A CCB may ease vasospasm but won't save the hand if he keeps smoking."},
eli5="Smoking is what keeps inflaming and blocking his small arteries. If he stops completely, the disease stops. If he doesn't, he can lose fingers."),

dict(img='Vphleg', cap='Photograph of the legs',
stem="A 58-year-old woman with metastatic ovarian cancer has 2 days of rapidly increasing swelling and severe pain in her left leg, which is now tense, mottled and bluish (shown). Pedal pulses are faint. Duplex shows occlusive thrombus from the common femoral vein through the iliac veins.{FIG}Which of the following best describes this condition?",
choices=["Phlegmasia cerulea dolens","Phlegmasia alba dolens","Post-thrombotic syndrome","Acute arterial embolus","Cellulitis"], key=0,
exp="Massive iliofemoral DVT has caused <b>phlegmasia cerulea dolens</b>: the <b>painful blue leg</b>, the <b>reversible phase of ischemic venous occlusion</b>, with a predisposition to limb loss. Untreated, it progresses to <b>venous gangrene</b> (irreversible). <b>Phlegmasia alba dolens</b> (\"milk leg\") is the earlier, non-ischemic form: massive edema and <b>white blanching</b>. Note: the recording called alba \"arterial\"; both are venous. Management: anticoagulation plus urgent thrombus removal (catheter-directed thrombolysis or thrombectomy). Cancer → long-term LMWH.<br><br><b>Educational objective:</b> A massively swollen, painful, blue leg from iliofemoral DVT is phlegmasia cerulea dolens, a limb-threatening emergency.",
wrong={1:"Alba dolens is the white, non-ischemic stage.",
2:"Post-thrombotic syndrome is chronic (years later).",
3:"An arterial embolus gives a pale, cold, pulseless but <b>not</b> massively swollen leg.",
4:"Cellulitis doesn't cause massive venous occlusion on duplex."},
eli5="The clot blocked all the veins draining her leg, so blood can't get out. The leg swells so much that fresh blood can't get in either, and it turns blue."),

dict(img='Ahollen', cap='Fundus photograph of the right eye',
stem="A 70-year-old man had three episodes this month of painless vision loss in his right eye, \"like a shade coming down,\" each lasting about 5 minutes. His fundus is shown. A soft bruit is heard over the right neck.{FIG}Which of the following is the most appropriate next test?",
choices=["Carotid duplex ultrasonography","Temporal artery biopsy","Brain MRI with gadolinium only","Lumbar puncture","Electroencephalogram"], key=0,
exp="Transient monocular blindness is <b>amaurosis fugax</b>: emboli from the <b>carotid bifurcation</b> to the retinal artery. The fundus shows bright, refractile <b>Hollenhorst plaques</b> (cholesterol emboli) at retinal artery branch points, with retinal whitening. Work-up: <b>carotid duplex</b> is the primary screening test for grading carotid stenosis (then angiography for the intervention). Echocardiography looks for a cardiac source. Symptomatic stenosis > 70% → endarterectomy.<br><br><b>Educational objective:</b> Amaurosis fugax with Hollenhorst plaques signals carotid embolic disease. Grade the stenosis with carotid duplex.",
wrong={1:"Temporal artery biopsy is for GCA (headache, jaw claudication, high ESR).",
2:"MRI shows brain ischemia but doesn't grade the carotid lesion.",
3:"LP has no role in embolic vision loss.",
4:"EEG is for seizures."},
eli5="Little cholesterol bits from a narrowed neck artery keep blocking the eye's artery for a few minutes. An ultrasound of the neck artery shows how narrow it is."),

dict(img='Apseudo', cap='Photograph of the right groin and thigh',
stem="The day after a coronary angiogram through the right femoral artery, a 69-year-old woman has groin pain and the swelling shown. There is a tender, pulsatile, expansile mass with a systolic bruit over the puncture site; distal pulses are normal.{FIG}Which of the following is the most likely diagnosis?",
choices=["Femoral artery pseudoaneurysm","Arteriovenous fistula","Simple groin hematoma","Deep venous thrombosis","Inguinal hernia"], key=0,
exp="A <b>pulsatile, expansile</b> mass with a <b>systolic bruit</b> at the puncture site after femoral access is a <b>pseudoaneurysm</b>: a contained leak through the arterial wall held by surrounding tissue. Slide 17 lists the access-site complications of percutaneous procedures: <b>bleeding or hematoma, pseudoaneurysm, arteriovenous fistula</b>, iliac dissection, thrombosis and distal embolization. Board add-on: confirm with duplex; small ones may close on their own, and larger ones get ultrasound-guided thrombin injection or repair. An AV fistula gives a <b>continuous</b> bruit or thrill, and a hematoma isn't expansile.<br><br><b>Educational objective:</b> A pulsatile, expansile groin mass with a systolic bruit after femoral catheterization is a pseudoaneurysm.",
wrong={1:"An AV fistula produces a <b>continuous</b> bruit, often without an expansile mass.",
2:"A simple hematoma is a bruise that doesn't pulsate or expand.",
3:"DVT causes leg swelling, not a pulsatile groin mass.",
4:"A hernia isn't pulsatile and wouldn't appear right after catheterization."},
eli5="The hole left in the artery never sealed, so blood squirts into a pocket beside it with every heartbeat. That's the throbbing lump."),
]
