# Vascular Disease (Ciraulo) — Version 1, 18 items (6 with images): work-up, occlusive disease, acute ischemia, aorta, viscera, veins
Q = [
dict(img=None,
stem="Two patients see their primary care physician for leg pain. A 66-year-old man who smokes gets cramping in his right calf after walking two blocks; it goes away after 3 minutes of standing still. A 71-year-old woman with chronic low back pain gets burning, tingling pain down both legs while standing at the kitchen sink; it eases when she sits down and leans forward. Both have normal pedal pulses at rest.{FIG}Which of the following best characterizes the woman's symptoms?",
choices=["Neurogenic claudication from spinal stenosis","Intermittent claudication from femoropopliteal disease","Critical limb ischemia with rest pain","Aortoiliac disease with buttock claudication","Venous claudication from post-thrombotic syndrome"], key=0,
exp="The lecture contrasts two kinds of claudication.<br>• <b>Vascular (intermittent) claudication</b>: muscle pain (usually the calf) brought on by walking, <b>reproducible</b>, relieved by <b>rest</b>. That's the man.<br>• <b>Neurogenic claudication</b>: a history of <b>back pain</b>, pain that <b>radiates</b> down the leg with <b>paresthesia</b>, and it can come on just <b>standing</b>. That's the woman. Board add-on: relieved by sitting or bending forward (lumbar flexion widens the canal), and pulses are normal.<br><br><b>Educational objective:</b> Neurogenic claudication (lumbar stenosis) gives radiating pain with paresthesia on standing, relieved by flexion. Vascular claudication is exertional and relieved by rest.",
wrong={1:"Vascular claudication is brought on by walking and relieved by standing still, not posture-dependent.",
2:"Rest pain is ischemic pain in the forefoot at night, relieved by dangling the leg. Her pulses are normal.",
3:"Aortoiliac claudication is exertional buttock and thigh pain, usually with weak femoral pulses.",
4:"Venous claudication comes with swelling, pigmentation and ulcers after a DVT."},
eli5="Her pain comes from pinched nerves in the lower back. Standing squeezes them and leaning forward opens up space. Blocked arteries hurt when the muscles work, not when you stand."),

dict(img=None,
stem="A 68-year-old man with diabetes has calf pain on walking. Systolic blood pressures are 150 mm Hg in the right arm and 140 mm Hg in the left arm. The right ankle pressure is 75 mm Hg and the left ankle pressure is 146 mm Hg.{FIG}Which of the following is his right ankle-brachial index?",
choices=["0.50","0.54","0.97","1.04","2.00"], key=0,
exp="Lecture formula: <b>ABI = ankle systolic pressure ÷ the higher of the two brachial pressures</b>. Right: 75 ÷ <b>150</b> = <b>0.50</b>. (Dividing by the left arm, 140, gives 0.54, the classic error.) Left: 146 ÷ 150 = 0.97. A low value, <b>especially when one side differs from the other</b>, is abnormal. Board add-on cut-offs: ≥ 1.0 normal · ≤ 0.9 PAD · < 0.4 severe · > 1.4 non-compressible (diabetes, CKD).<br><br><b>Educational objective:</b> Calculate the ABI by dividing each ankle pressure by the higher brachial pressure.",
wrong={1:"0.54 uses the lower arm pressure (140). Always use the higher brachial pressure.",
2:"0.97 is the left leg.",
3:"1.04 divides the left ankle by the lower arm.",
4:"2.00 inverts the ratio (arm ÷ ankle)."},
eli5="Divide the ankle pressure by the bigger of the two arm pressures: 75 ÷ 150 = 0.5. Half the expected pressure reaches that ankle."),

dict(img=None,
stem="A 72-year-old man has a pulsatile abdominal mass. An aortogram done at another hospital showed a contrast-filled aortic lumen 2.4 cm wide, and he was told his aorta was \"normal size.\"{FIG}Which of the following is the most appropriate study to determine the true diameter of his aorta?",
choices=["CT with contrast","Repeat aortogram with more contrast","Plain abdominal x-ray","Serum D-dimer level","Exercise ankle-brachial index"], key=0,
exp="Dr. Ciraulo's trick question: \"The way they trick you on exams is to say the hallmark for making this diagnosis is an aortogram. That's not true.\" An angiogram shows only where the <b>dye flows</b> (the lumen). <b>Mural thrombus</b> can line a large aneurysm, leaving a narrow channel that looks normal. <b>CT shows the outer diameter of the pipe and the thrombus</b>. For AAA: ultrasound screens, <b>CT with contrast is the gold standard</b>. Angiography is used on the table, when sizing a stent graft.<br><br><b>Educational objective:</b> CT measures the true (outer-wall) diameter of an aneurysm. An angiogram shows only the lumen and can miss an aneurysm lined with thrombus.",
wrong={1:"More contrast still shows only the lumen, not the thrombus-filled wall.",
2:"A plain film may show an eggshell rim of calcium but can't measure size reliably.",
3:"D-dimer is a nonspecific clotting marker, not an aneurysm study.",
4:"The ABI assesses limb perfusion, not aortic size."},
eli5="Dye only shows the open channel. If the aneurysm is lined with clot, the channel looks normal even though the wall has ballooned. CT shows the whole wall."),

dict(img=None,
stem="A 59-year-old man asks for a prescription for sildenafil. Over the past year he has developed erectile dysfunction and aching in both buttocks and thighs when he climbs ladders at work, which settles with rest. Femoral pulses are weak bilaterally.{FIG}Which of the following is the most likely location of his arterial disease?",
choices=["Aortic bifurcation and iliac arteries","Superficial femoral artery in the thigh","Popliteal artery","Tibial arteries below the knee","Internal pudendal arteries only"], key=0,
exp="This is <b>Leriche syndrome</b>: <b>buttock (and thigh) claudication, impotence and diminished femoral pulses</b>, in men. It's aortoiliac occlusive disease at the level of the aortic bifurcation. Dr. Ciraulo: \"Don't just write a prescription for Viagra.\" The hallmark of aortoiliac disease is <b>diminished or absent femoral pulses</b>. \"Every time you have a name on something, you can almost count it being a test question.\"<br><br><b>Educational objective:</b> Buttock claudication + erectile dysfunction + weak femoral pulses = Leriche syndrome (aortoiliac occlusion).",
wrong={1:"SFA disease causes calf claudication with palpable femoral pulses.",
2:"Popliteal disease causes calf symptoms, and the femoral pulses are normal.",
3:"Tibial disease (diabetes, dialysis) presents with foot ulcers and gangrene.",
4:"Isolated pudendal disease wouldn't cause buttock claudication or weak femoral pulses."},
eli5="The big artery that splits to feed both legs and the pelvis is blocked at the split. That starves the buttocks and the penis and weakens the pulses in both groins."),

dict(img=None,
stem="A 64-year-old woman has lifestyle-limiting calf claudication. She has quit smoking and takes aspirin and atorvastatin. She has heart failure with an ejection fraction of 25%. She asks about a medicine that helps people walk farther.{FIG}Why should cilostazol be avoided in this patient?",
choices=["It's contraindicated in heart failure","It interacts dangerously with aspirin","It causes rhabdomyolysis with statins","It worsens claudication at first","It is ineffective in women"], key=0,
exp="<b>Cilostazol</b> is a <b>phosphodiesterase-3 inhibitor</b> that causes vasodilation (smooth-muscle relaxation) and inhibits platelet aggregation. It's the drug shown to improve claudication. It is <b>contraindicated in congestive heart failure</b> (board add-on: PDE3 inhibitors such as milrinone raised mortality in HF). Her other options: a <b>graded exercise programme</b> (very effective, promotes collaterals), smoking cessation, antiplatelet therapy and a statin. Intervene for lifestyle-limiting claudication, rest pain or tissue loss.<br><br><b>Educational objective:</b> Cilostazol (a PDE3 inhibitor) improves claudication but is contraindicated in heart failure.",
wrong={1:"It can be combined with aspirin (bleeding risk is modestly additive).",
2:"Rhabdomyolysis is a statin–fibrate problem, not cilostazol.",
3:"It doesn't worsen claudication.",
4:"It works in both sexes."},
eli5="The walking pill belongs to the same family as a heart drug that made heart-failure patients die sooner, so it's off-limits with a weak heart."),

dict(img=None,
stem="A 74-year-old man has a cold, pale, pulseless left leg after a sudden onset of pain 5 hours ago. Heparin is started and catheter-directed thrombolysis is being considered.{FIG}Which of the following findings in his history is an absolute contraindication to thrombolysis?",
choices=["Ischemic stroke 6 weeks ago","Knee arthroscopy 5 weeks ago","Atrial fibrillation","Age over 70 years","Prior coronary artery bypass 10 years ago"], key=0,
exp="Slide 31's absolute contraindications to thrombolysis: <b>recent stroke or brain surgery within 2 months</b>, <b>major surgery within 2 weeks</b>, and patients at significant bleeding risk. A stroke 6 weeks ago falls inside the 2-month window. The arthroscopy (5 weeks, minor) does not. Atrial fibrillation is the likely <b>cause</b> of the embolus. If lysis is out, the alternative is <b>open Fogarty embolectomy</b>. Lysis is preferred when motor and sensory function are intact.<br><br><b>Educational objective:</b> Thrombolysis is absolutely contraindicated after stroke or brain surgery within 2 months, major surgery within 2 weeks, or with significant bleeding risk.",
wrong={1:"Surgery is a contraindication only within 2 weeks, and arthroscopy is minor.",
2:"AF is the likely embolic source, not a contraindication.",
3:"Age alone isn't an absolute contraindication.",
4:"Remote cardiac surgery doesn't contraindicate lysis."},
eli5="Clot-busting drugs dissolve any clot, including the one sealing a recently damaged spot in the brain. So a stroke in the last 2 months rules them out."),

dict(img=None,
stem="A 52-year-old man with hypertension presents with sudden tearing pain between his shoulder blades. CT angiography shows a dissection limited to the ascending aorta that ends before the brachiocephalic artery.{FIG}Which of the following is the most appropriate management?",
choices=["Emergent open surgical repair","Blood-pressure control alone","Thoracic endovascular repair as first choice","Thrombolytic therapy","Observation with repeat CT in 2 weeks"], key=0,
exp="A dissection limited to the ascending aorta is <b>DeBakey II</b> (\"starts at the root, stays at the root\"; 10–15%), which is <b>Stanford A</b>. DeBakey I (root → descending, 60%) is also Stanford A. DeBakey III (distal to the left subclavian, 25–30%) is Stanford B.<br>• <b>Type A → emergent open repair</b> (root ± valve; arch → re-implant the arch vessels).<br>• <b>Uncomplicated type B → medical BP control</b>, with TEVAR if it fails or becomes complicated.<br><br><b>Educational objective:</b> Any dissection involving the ascending aorta (Stanford A = DeBakey I and II) needs emergent open repair.",
wrong={1:"BP control alone is for uncomplicated <b>type B</b> dissections. It's part of initial care here but not definitive.",
2:"TEVAR is the preferred intervention for <b>complicated type B</b> dissections.",
3:"Thrombolysis in a dissection would be catastrophic.",
4:"Type A dissection is a surgical emergency, not something to watch."},
eli5="A tear right next to the heart can burst into the heart sac or tear the aortic valve, so surgeons fix it immediately. Tears farther down are usually managed by lowering blood pressure."),

dict(img=None,
stem="A 70-year-old man who smoked for 45 years has an asymptomatic abdominal aortic aneurysm measuring 4.7 cm on ultrasound. He has no family history of aneurysm.{FIG}Which of the following is the most appropriate plan?",
choices=["Ultrasound every 3 months","Ultrasound every 6 months","Open or endovascular repair now","Yearly CT for 5 years","No follow-up is needed"], key=0,
exp="Dr. Ciraulo: \"You're gonna have something on this on the test, so make sure you memorize this.\"<br>• <b>< 4.5 cm</b>: ultrasound every <b>6 months</b>.<br>• <b>4.5–5.0 cm</b>: ultrasound every <b>3 months</b> (chart: 3–6). \"You're in the danger zone.\"<br>• <b>5.0–5.5 cm</b>: repair if female, familial, proven rapid growth (otherwise every 3–6 months).<br>• <b>> 5.5 cm</b>: repair.<br>Also repair if <b>symptomatic</b>, growth <b>> 5 mm in 6 months</b>, or saccular/eccentric shape. And stop smoking.<br><br><b>Educational objective:</b> An asymptomatic AAA of 4.5–5.0 cm is followed with ultrasound every 3 months.",
wrong={1:"Every 6 months is for aneurysms under 4.5 cm.",
2:"Repair is indicated above 5.5 cm, when symptomatic, or with rapid growth.",
3:"Ultrasound is the surveillance tool. Yearly is too infrequent at this size.",
4:"Any AAA needs surveillance."},
eli5="At 4.7 cm the aneurysm is getting close to the size where surgery is needed, so it gets checked often, every 3 months."),

dict(img=None,
stem="A 71-year-old man had open repair of an abdominal aortic aneurysm with a Dacron graft 6 years ago. He vomits a small amount of bright red blood; several hours later he has massive hematemesis and becomes hypotensive.{FIG}Which of the following is the most likely diagnosis?",
choices=["Aortoenteric fistula","Bleeding duodenal ulcer","Esophageal variceal bleed","Mallory-Weiss tear","Ischemic colitis"], key=0,
exp="An <b>aortoenteric (aortoduodenal) fistula</b>: the aortic graft (or aneurysm) erodes into the third or fourth part of the duodenum. A known aneurysm or graft + GI bleeding \"like a hose\" is the nightmare Dr. Ciraulo described. Board add-on: a small <b>herald bleed</b> often precedes the exsanguinating one. Diagnosis: endoscopy (and CT). Treatment: <b>graft removal and extra-anatomic bypass</b>, sometimes after a temporizing stent graft.<br><br><b>Educational objective:</b> GI bleeding in a patient with an aortic graft or aneurysm is an aortoenteric fistula until proven otherwise.",
wrong={1:"Ulcers bleed, but the graft history makes a fistula the must-not-miss diagnosis.",
2:"Varices need portal hypertension, which isn't described.",
3:"A Mallory-Weiss tear follows forceful vomiting and is usually self-limited.",
4:"Ischemic colitis causes bloody diarrhea, typically within days of aortic surgery, not hematemesis years later."},
eli5="Over the years the aortic graft has worn a hole into the intestine next to it, so aortic blood pours straight into the gut."),

dict(img=None,
stem="A 56-year-old woman who smokes has had crampy periumbilical pain starting about 30 minutes after every meal for 6 months. She has lost 9 kg because she has become afraid to eat. Examination between episodes is unremarkable.{FIG}Which of the following is the diagnostic study of choice?",
choices=["CT angiography","Upper endoscopy","Gallbladder ultrasound","Colonoscopy","Mesenteric duplex as the only test"], key=0,
exp="<b>Chronic mesenteric ischemia</b> (\"intestinal angina\"): slow atherosclerotic stenosis. Blood flow normally rises <b>30–90 minutes after a meal</b>, and the narrowed vessels can't meet the demand. Classic patient: <b>middle-aged woman, postprandial pain, weight loss</b> (food fear). Diagnosis: mesenteric duplex (~80% sensitive and specific) · <b>CTA = diagnostic modality of choice</b> · mesenteric angiogram = gold standard, used with endovascular treatment. Treatment: <b>revascularize</b> (endovascular or bypass) to prevent bowel infarction.<br><br><b>Educational objective:</b> Chronic mesenteric ischemia (postprandial pain, food fear, weight loss) is diagnosed with CT angiography and treated with revascularization.",
wrong={1:"Endoscopy looks for ulcers, but the meal timing and weight loss point to the vessels.",
2:"Biliary colic doesn't cause consistent post-meal pain with food fear and weight loss.",
3:"Colonoscopy doesn't evaluate the mesenteric arteries.",
4:"Duplex is a screen (~80%), but CTA is the diagnostic modality of choice."},
eli5="Her gut arteries are narrowed. After she eats, the gut needs more blood and can't get it, so it hurts. She stops eating and loses weight."),

dict(img=None,
stem="A 63-year-old man is on day 7 of unfractionated heparin after hip replacement. His platelet count has fallen from 260,000 to 95,000/µL, and he has a new thrombosis of the right femoral artery.{FIG}Which of the following is the most appropriate next step?",
choices=["Stop heparin and start argatroban","Switch to enoxaparin for the rest of the course","Start warfarin immediately","Transfuse platelets","Continue heparin and add aspirin"], key=0,
exp="This is <b>heparin-induced thrombocytopenia (HIT)</b>: IgG against the <b>heparin–platelet factor 4</b> complex → immune complexes activate platelets via Fc receptors → <b>thrombocytopenia and thrombosis</b> during or right after heparin. Lab: heparin–PF4 antibody, platelet aggregation, <b>serotonin release assay</b>. Treatment: <b>stop all heparin immediately</b> (including flushes and LMWH) and start a <b>direct thrombin inhibitor</b>: argatroban, lepirudin or bivalirudin. Board add-on: typically day 5–10; don't start warfarin until platelets recover (venous limb gangrene).<br><br><b>Educational objective:</b> HIT is treated by stopping all heparin and starting a direct thrombin inhibitor such as argatroban.",
wrong={1:"LMWH cross-reacts with HIT antibodies. All heparin must stop.",
2:"Warfarin started acutely in HIT can cause venous limb gangrene.",
3:"Platelet transfusion can fuel thrombosis in HIT.",
4:"Continuing heparin keeps driving the antibody reaction."},
eli5="His immune system is reacting to heparin in a way that both uses up platelets and makes clots. Stop all heparin and switch to a different kind of blood thinner."),

dict(img=None,
stem="A 34-year-old man with a traumatic subdural hematoma and a pelvic fracture is found on day 4 to have a deep venous thrombosis of the left common femoral vein.{FIG}Which of the following is the most appropriate management?",
choices=["Placement of a retrievable IVC filter","Full-dose heparin infusion","Warfarin with an INR goal of 2–3","Catheter-directed thrombolysis","Aspirin and compression stockings only"], key=0,
exp="Acute DVT is normally treated with <b>anticoagulation</b> to prevent PE and propagation. But anticoagulation is <b>contraindicated</b> with an intracranial bleed (Dr. Ciraulo's trauma service: subdurals, epidurals). Slide 82: <b>IVC filters are used when anticoagulation is contraindicated</b>, placed immediately to prevent PE. <b>Prefer a retrievable filter</b>, removed with a snare on its hook once the risk has passed or anticoagulation is possible. Untreated proximal DVT carries a 30–50% PE risk.<br><br><b>Educational objective:</b> A DVT in a patient who can't be anticoagulated is treated with a (retrievable) IVC filter.",
wrong={1:"Full anticoagulation risks expanding the subdural hematoma.",
2:"Warfarin is also anticoagulation, so it's contraindicated now.",
3:"Thrombolysis is even more dangerous with an intracranial bleed.",
4:"Aspirin and stockings don't protect against PE from a proximal DVT."},
eli5="He can't take blood thinners because his brain is bleeding, so doctors put a little metal net in the big vein to catch clots before they reach the lungs."),

dict(img='Advt', cap='Photograph of the legs',
stem="A 58-year-old woman develops swelling and aching of her left leg 9 days after a total knee replacement. The calf is warm and tender, and dorsiflexing her ankle hurts. Her legs are shown.{FIG}Which of the following is the most appropriate test to confirm the diagnosis?",
choices=["Duplex ultrasonography","D-dimer level","Contrast venography","CT pulmonary angiography","Ankle-brachial index"], key=0,
exp="Post-orthopedic surgery, unilateral swelling, warmth, calf tenderness and pain on passive dorsiflexion (<b>Homans sign</b>) → <b>deep venous thrombosis</b>. Without prophylaxis, DVT occurs in 50–60% of orthopedic surgery patients. Dr. Ciraulo: get a <b>duplex ultrasound</b>. \"We'll tell you what's going on.\" <b>D-dimer</b> is nonspecific (positive after any surgery); board add-on: it only rules out DVT when pretest probability is low. MR venography is best for iliac, pelvic and central veins. Contrast venography is of historical interest.<br><br><b>Educational objective:</b> Duplex ultrasonography is the diagnostic test for suspected DVT. D-dimer is nonspecific, especially after surgery.",
wrong={1:"D-dimer is almost always raised after major surgery and can't confirm DVT.",
2:"Contrast venography is mostly of historical interest.",
3:"CT pulmonary angiography looks for PE. She has no chest symptoms.",
4:"The ABI assesses arteries, not veins."},
eli5="An ultrasound can actually see the clot in the leg vein and show whether blood flows past it."),

dict(img='Acarotid', cap='Selective carotid angiogram',
stem="A 69-year-old man had two episodes of right-hand weakness and slurred speech, each lasting about 20 minutes. Neurologic examination is now normal. Duplex ultrasound and the angiogram shown demonstrate an 80% stenosis of the left internal carotid artery.{FIG}In addition to aspirin and a statin, which of the following is the most appropriate management?",
choices=["Left carotid endarterectomy","Medical therapy alone, with repeat duplex","Right carotid endarterectomy","Lifelong warfarin","Vertebral artery angioplasty"], key=0,
exp="These were <b>TIAs</b> (< 24 h) in the left carotid territory, so the stenosis is <b>symptomatic</b>. Slide 39: in <b>symptomatic stenosis > 70%</b>, surgery lowers the 2-year stroke risk from <b>26% to 9%</b>. \"If you have a 70% stenosis, you probably are going to be getting teed up for an intervention.\" <b>Carotid endarterectomy</b>: remove the plaque, patch closure, shunt for brain perfusion; watch for <b>hypoglossal and vagus nerve injury</b>. Stenting is for lesions at the skull base or patients too sick for surgery. Contraindications: disabling stroke, occluded ICA, short life expectancy.<br><br><b>Educational objective:</b> Symptomatic carotid stenosis > 70% is treated with carotid endarterectomy plus medical therapy.",
wrong={1:"Medical therapy alone leaves a 26% 2-year stroke risk in symptomatic > 70% stenosis.",
2:"The symptomatic lesion is on the left (right-hand weakness and aphasia).",
3:"Warfarin is for cardiac emboli (AF), not carotid plaque.",
4:"His symptoms are anterior circulation (carotid), not vertebrobasilar."},
eli5="A big plaque in his left neck artery keeps throwing small clots to the brain. Cleaning the plaque out greatly cuts his stroke risk."),

dict(img='Avenulcer', cap='Photograph of the medial lower leg',
stem="A 64-year-old woman had an iliofemoral deep venous thrombosis 4 years ago. She now has chronic leg swelling, aching that worsens by evening, brown pigmentation of the skin and the shallow wound shown above the medial malleolus.{FIG}Which of the following is the cornerstone of treatment?",
choices=["Compression therapy and leg elevation","Lifelong high-dose warfarin","Below-knee amputation","Femoropopliteal arterial bypass with vein","Systemic thrombolysis"], key=0,
exp="<b>Post-thrombotic syndrome</b>: the chronic complication of DVT from <b>venous hypertension and valve damage</b>. Swelling, fatigue or pain, venous claudication, pigmentation (lipodermatosclerosis), eczema and <b>ulceration</b>, classically above the medial malleolus. Therapy: <b>elevation at rest and night, compression</b> (\"probably one of the most important things\"), pain control, wound care, and <b>iliac vein angioplasty/stenting</b> (iliac stenosis in 50–75% of PTS patients).<br><br><b>Educational objective:</b> Post-thrombotic syndrome (venous ulcer, pigmentation, swelling) is treated mainly with compression and elevation, plus iliac stenting when there's a venous stenosis.",
wrong={1:"Anticoagulation doesn't heal established valve damage or ulcers.",
2:"Amputation isn't indicated for venous ulceration.",
3:"Arterial bypass treats arterial disease, not venous hypertension.",
4:"The thrombus is 4 years old. Lysis won't restore valves now."},
eli5="The old clot wrecked the one-way valves in her leg veins, so blood pools and the skin breaks down. Squeezing the leg with compression helps push the blood back up."),

dict(img='Vgraftinf', cap='Axial CT of the abdomen with contrast',
stem="A 70-year-old man had an aortobifemoral bypass 3 years ago. He now has 3 weeks of dull abdominal pain, fevers and a white-cell count of 16,000/µL. His CT is shown.{FIG}Which of the following is the definitive treatment?",
choices=["Graft removal and extra-anatomic bypass","Six weeks of IV antibiotics alone","Percutaneous drain and keep the graft","Endovascular stent graft inside the old graft","Observation with repeat CT"], key=0,
exp="Dull abdominal pain, fever and leukocytosis in a patient with an aortic graft, with fluid and gas around the graft on CT, mean an <b>aortic graft infection</b>. Slide 54: antibiotics, <b>graft removal</b>, and an <b>extra-anatomic bypass</b> (for an infrarenal graft, an axillobifemoral bypass keeps the legs perfused outside the infected field). Dr. Ciraulo: \"Graft infections basically mean you take the damn graft out.\" Involvement of the renal or visceral arteries is \"a really bad day.\"<br><br><b>Educational objective:</b> Aortic graft infection requires graft removal with extra-anatomic bypass, plus antibiotics.",
wrong={1:"Antibiotics alone rarely sterilize an infected prosthetic graft.",
2:"Drainage alone leaves the infected foreign body in place.",
3:"Placing more prosthetic material in an infected field doesn't cure it.",
4:"An infected aortic graft can rupture or form a fistula. It can't be watched."},
eli5="Germs living on a plastic graft can't be cleared with antibiotics alone. The graft has to come out, and blood is rerouted through a new graft placed away from the infection."),

dict(img='Alivedo', cap='Photograph of the lower legs',
stem="Three weeks after a cardiac catheterization through the femoral artery, a 72-year-old man has the skin finding shown on both legs, several painful purple toes with normal pedal pulses, and a creatinine that has risen from 1.1 to 2.4 mg/dL.{FIG}Which of the following is the most likely cause?",
choices=["Atheroemboli from aortic plaque","Contrast-induced nephropathy alone","Femoral artery pseudoaneurysm","Deep venous thrombosis","Vasculitis from the contrast agent"], key=0,
exp="Livedo reticularis, <b>blue toes with palpable pulses</b> and acute kidney injury after a catheter procedure are <b>cholesterol (athero-) embolization</b>. Lecture: non-cardiac embolic sources include <b>iatrogenic atheroembolization after percutaneous vascular interventions</b>. <b>Microemboli</b> lodge in small distal and digital vessels → <b>blue toe syndrome</b>, and in the kidneys. Board add-on: eosinophilia, low complement, and cholesterol clefts on biopsy. Contrast nephropathy peaks in 2–5 days and doesn't cause skin or toe findings.<br><br><b>Educational objective:</b> Blue toes with normal pulses, livedo reticularis and kidney injury after catheterization mean cholesterol embolization.",
wrong={1:"Contrast nephropathy occurs within days and doesn't explain the skin and toes.",
2:"A pseudoaneurysm gives a pulsatile groin mass.",
3:"DVT gives a swollen leg, not blue toes with livedo.",
4:"Contrast doesn't cause vasculitis."},
eli5="The catheter scraped bits of cholesterol off the aorta wall. They showered downstream and plugged tiny arteries in the toes, skin and kidneys."),

dict(img='Vcfa', cap='Digital subtraction angiogram of the right groin and thigh',
stem="A 66-year-old woman has disabling right-thigh and calf claudication. Her right femoral pulse is absent. The angiogram shows a short occlusion confined to the common femoral artery, with the profunda and superficial femoral arteries reconstituting below it.{FIG}Which procedure best suits this localized lesion?",
choices=["Femoral endarterectomy with patch","Axillobifemoral bypass","Below-knee popliteal-to-tibial bypass","Aortobifemoral bypass","Lumbar sympathectomy"], key=0,
exp="Slide 24: <b>local endarterectomy of the common femoral and profunda with patch angioplasty</b> is \"good for local lesions.\" The common femoral sits in the groin where stents fare poorly (it bends with the hip), and the <b>profunda</b> is the key thigh and buttock supply and collateral source. Dr. Ciraulo: \"where the endarterectomy is pretty helpful is the profunda.\" Bypass is for longer occlusions. Axillobifemoral bypass is a long extra-anatomic route for high-risk aortoiliac disease. Aortobifemoral bypass treats aortoiliac disease.<br><br><b>Educational objective:</b> A focal common femoral/profunda lesion is treated with endarterectomy and patch angioplasty.",
wrong={1:"Axillobifemoral bypass is a long extra-anatomic graft for high-risk aortoiliac disease.",
2:"Tibial bypass treats below-knee disease.",
3:"Aortobifemoral bypass treats aortoiliac disease. Her aorta and iliacs aren't the problem.",
4:"Sympathectomy is a rare option for vasospasm (Raynaud), not occlusive disease."},
eli5="The blockage is short and right in the groin, so the surgeon opens the artery, scoops out the plaque and patches it closed."),
]
